# DNB Seasonal

For data from CLASS
* JPSS VIIRS EDR: https://www.avl.class.noaa.gov/saa/products/search?datatype_family=VIIRS_EDR
* Search criteria for Georges Bank: https://drive.google.com/file/d/1P-OtjgAO_0DWUfhJDFEOWzMWmLIQSYj7/view?usp=share_link

In [1]:
import xarray as xr
import h5py
import numpy as np
import satpy
from glob import glob

In [2]:
dnb_path = '/mnt/data2/jturner/dnb_data/georges_bank/'
dnb_file = 'GNCCO-VNCCO_npp_d20230105_t0521191_e0527239_b57982_c20231204164854556487_oeac_ops.h5'

In [3]:
filenames = glob('/mnt/data2/jturner/dnb_data/georges_bank/*')
filenames

['/mnt/data2/jturner/dnb_data/georges_bank/GNCCO-VNCCO_npp_d20230103_t0556212_e0602224_b57954_c20231204164451483332_oeac_ops.h5',
 '/mnt/data2/jturner/dnb_data/georges_bank/GNCCO-VNCCO_npp_d20230105_t0521191_e0527239_b57982_c20231204164854556487_oeac_ops.h5',
 '/mnt/data2/jturner/dnb_data/georges_bank/GNCCO-VNCCO_npp_d20230104_t0538511_e0544540_b57968_c20231204164350189320_oeac_ops.h5']

Satpy needs a reader that matches to the data: 
* https://satpy.readthedocs.io/en/stable/index.html#reader-table
* https://nbviewer.org/github/pytroll/pytroll-examples/blob/main/satpy/Cartopy%20Plot.ipynb


In [4]:
ds = xr.open_dataset(dnb_path+dnb_file, engine="h5netcdf")
ds

<xarray.Dataset>
Dimensions:  ()
Data variables:
    *empty*
Attributes:
    Distributor:          arch
    Mission_Name:         S-NPP/JPSS
    N_Dataset_Source:     oea-
    N_HDF_Creation_Date:  20231204
    N_HDF_Creation_Time:  164854.556487Z
    Platform_Short_Name:  NPP

In [8]:
f = h5py.File(dnb_path+dnb_file, 'r')

In [13]:
list(f['All_Data']['VIIRS-NCC-EDR_All'].keys())

['Albedo', 'AlbedoFactors', 'PadByte1', 'QF1_VIIRSNCCEDR']

In [15]:
list(f['All_Data']['VIIRS-NCC-EDR_All']['QF1_VIIRSNCCEDR'])

[array([129, 129, 129, ..., 129, 129, 129], dtype=uint8),
 array([129, 129, 129, ..., 129, 129, 129], dtype=uint8),
 array([129, 129, 129, ..., 129, 129, 129], dtype=uint8),
 array([129, 129, 129, ..., 129, 129, 129], dtype=uint8),
 array([129, 129, 129, ..., 129, 129, 129], dtype=uint8),
 array([129, 129, 129, ..., 129, 129, 129], dtype=uint8),
 array([129, 129, 129, ..., 129, 129, 129], dtype=uint8),
 array([129, 129, 129, ..., 129, 129, 129], dtype=uint8),
 array([129, 129, 129, ..., 129, 129, 129], dtype=uint8),
 array([129, 129, 129, ..., 129, 129, 129], dtype=uint8),
 array([129, 129, 129, ..., 129, 129, 129], dtype=uint8),
 array([129, 129, 129, ..., 129, 129, 129], dtype=uint8),
 array([129, 129, 129, ..., 129, 129, 129], dtype=uint8),
 array([129, 129, 129, ..., 129, 129, 129], dtype=uint8),
 array([129, 129, 129, ..., 129, 129, 129], dtype=uint8),
 array([129, 129, 129, ..., 129, 129, 129], dtype=uint8),
 array([129, 129, 129, ..., 129, 129, 129], dtype=uint8),
 array([129, 1

In [9]:
list(f['Data_Products']['VIIRS-NCC-EDR'].keys())

['VIIRS-NCC-EDR_Aggr',
 'VIIRS-NCC-EDR_Gran_0',
 'VIIRS-NCC-EDR_Gran_1',
 'VIIRS-NCC-EDR_Gran_2',
 'VIIRS-NCC-EDR_Gran_3']

In [10]:
list(f['Data_Products']['VIIRS-NCC-EDR']['VIIRS-NCC-EDR_Gran_0'])

[<HDF5 region reference>,
 <HDF5 region reference>,
 <HDF5 region reference>,
 <HDF5 region reference>]